# Generated by Django 3.1.2 on 2020-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201022_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click The Link Above To Head To The Post', max_length=255),
        ),
    ]
